apiVersion: v1
kind: Service
metadata:
  name: fibos-node-snapshot-backup
  labels:
    app: fibos-node-snapshot-backup
spec:
  ports:
  - port: 8888
  selector:
    app: fibos-node-snapshot-backup
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fibos-node-snapshot-backup
  labels:
    app: fibos-node-snapshot-backup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fibos-node-snapshot-backup
  template:
    metadata:
      labels:
        app: fibos-node-snapshot-backup
    spec:
      containers:
        - image: mingfunwong/fibos
          imagePullPolicy: Always
          name: fibos
          env:
            - name: PRODUCER_API_ENABLE
              value: 'true'
            - name: SNAPSHOT_ENABLE
              value: 'true'
            - name: SNAPSHOT_URL
              value: https://github.com/andy-backup/fibos/raw/master/snapshot.bin
          volumeMounts:
            - mountPath: /fibos/data
              name: snapshot-volume
        - image: mingfunwong/snapshot-backup
          imagePullPolicy: Always
          name: snapshot
          env:
            - name: GITHUB
              value: git@github.com:andy-backup/fibos.git
            - name: GIT_USER_EMAIL
              value: mingfun.wong.chn@gmail.com
            - name: GIT_USER_NAME
              value: Mingfun Wong
            - name: SNAPSHOT_URL
              value: http://fibos-node-snapshot-backup:8888/v1/producer/create_snapshot
            - name: CRON
#                    min   hour    day     month   weekday
              value: "0     */12    *       *       *"
          volumeMounts:
            - mountPath: /data/local
              name: snapshot-volume
            - name: ssh-key-pub
              mountPath: /data/.ssh/id_rsa.pub
              subPath: id_rsa
            - name: ssh-key-pri
              mountPath: /data/.ssh/id_rsa
              subPath: id_rsa
      volumes:
        - name: ssh-key-pub
          configMap:
            name: ssh-key-pub
        - name: ssh-key-pri
          configMap:
            name: ssh-key-pri
        - name: snapshot-volume
          emptyDir: {}

